# -*- coding: utf-8 -*-
"""Primera entrega

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lT0uFhAcVyfzNCa0mvEZmIi7Nb5GkW7K

Taller 1 de métodos matemáticos

Ejercicio 5 sección 1.1.6
"""

import sympy as sp

#Parte a
#Definir el lado del cuadrado
a = 2

#Definir las masas
m1, m2, m3, m4 = 1, 2, 3, 4

#Definir las posiciones de los vértices del cuadrado (x, y)
r1 = sp.Matrix([0, 0])
r2 = sp.Matrix([a, 0])
r3 = sp.Matrix([a, a])
r4 = sp.Matrix([0, a])

#Masa total
M = m1 + m2 + m3 + m4

#Calcular el centro de masa
r_cm = (m1*r1 + m2*r2 + m3*r3 + m4*r4) / M

print(r_cm)

#Parte b
#Definimos lados del cubo
a = 2

#Definir las masas
m1, m2, m3, m4 = 1, 2, 3, 4
m5, m6, m7, m8 = 5, 6, 7, 8

#Definir las posiciones de los vértices del cuadrado (x, y)
r1 = sp.Matrix([0, 0, 0])
r2 = sp.Matrix([a, 0, 0])
r3 = sp.Matrix([a, a, 0])
r4 = sp.Matrix([0, a, 0])

r5 = sp.Matrix([0, 0, a])
r6 = sp.Matrix([a, 0, a])
r7 = sp.Matrix([a, a, a])
r8 = sp.Matrix([0, a, a])

#Masa total
M = m1 + m2 + m3 + m4 + m5 + m6 + m7 + m8

#Calcular el centro de masa
R_cm = (m1*r1 + m2*r2 + m3*r3 + m4*r4 + m5*r5 + m6*r6 + m7*r7 + m8*r8) / M

print(R_cm)

"""Ejercicio 6 sección 1.2.7"""

# Importar sympy
import sympy
from sympy import *
from sympy.vector import *

# SISTEMA DE COORDENADAS
R = CoordSys3D('R')

# DEFINIR VECTORES DEL PROBLEMA
a = 1*R.i + 2*R.j + 3*R.k
b = 4*R.i + 5*R.j + 6*R.k
c = 3*R.i + 2*R.j + 1*R.k
d = 6*R.i + 5*R.j + 4*R.k

#Definir vectores base
e1 = R.i
e2 = R.j
e3 = R.k

# (a) SUMAS
s1 = a + b + c + d
s2 = a + b - c - d
s3 = a - b + c - d
s4 = -a + b - c + d

# (b) ANGULOS ENTRE VECTORES
# Ángulos del vector a con la base
theta_a_e1 = acos(a.dot(e1)/a.magnitude())
theta_a_e2 = acos(a.dot(e2)/a.magnitude())
theta_a_e3 = acos(a.dot(e3)/a.magnitude())

# Vector b
theta_b_e1 = acos(b.dot(e1)/b.magnitude())
theta_b_e2 = acos(b.dot(e2)/b.magnitude())
theta_b_e3 = acos(b.dot(e3)/b.magnitude())

# Vector c
theta_c_e1 = acos(c.dot(e1)/c.magnitude())
theta_c_e2 = acos(c.dot(e2)/c.magnitude())
theta_c_e3 = acos(c.dot(e3)/c.magnitude())

# Vector d
theta_d_e1 = acos(d.dot(e1)/d.magnitude())
theta_d_e2 = acos(d.dot(e2)/d.magnitude())
theta_d_e3 = acos(d.dot(e3)/d.magnitude())

# (c) MAGNITUDES
mag_a = a.magnitude()
mag_b = b.magnitude()
mag_c = c.magnitude()
mag_d = d.magnitude()

# (d) PRODUCTOS ESCALARES
dot_ab = a.dot(b)
dot_ac = a.dot(c)
dot_ad = a.dot(d)

# (e) PROYECCION DE a SOBRE
proj_a_b = (a.dot(b)/b.dot(b))*b

# (f) COPLANARIDAD (PRODUCTO TRIPLE)
triple = a.cross(b).dot(c)

# (g) (a + b) · (c + d)
dot_sum = (a + b).dot(c + d)

# (h) PRODUCTOS CRUZ
axb = a.cross(b)
bxc = b.cross(c)
cxd = c.cross(d)

# (i) c · (a × b)
triple2 = c.dot(a.cross(b))

# MOSTRAR RESULTADOS
# (a)
print("(a) Sumas vectoriales:")
print("suma 1=", s1)
print("suma 2=", s2)
print("suma 3=", s3)
print("suma 4=", s4)

# (b)

print("Vector a:")
print("θ(a, e1) =", theta_a_e1.evalf())
print("θ(a, e2) =", theta_a_e2.evalf())
print("θ(a, e3) =", theta_a_e3.evalf())

print("\nVector b:")
print("θ(b, e1) =", theta_b_e1.evalf())
print("θ(b, e2) =", theta_b_e2.evalf())
print("θ(b, e3) =", theta_b_e3.evalf())

print("\nVector c:")
print("θ(c, e1) =", theta_c_e1.evalf())
print("θ(c, e2) =", theta_c_e2.evalf())
print("θ(c, e3) =", theta_c_e3.evalf())

print("\nVector d:")
print("θ(d, e1) =", theta_d_e1.evalf())
print("θ(d, e2) =", theta_d_e2.evalf())
print("θ(d, e3) =", theta_d_e3.evalf())

# (c)
print("\n(c) Magnitudes:")
print("|a| =", mag_a)
print("|b| =", mag_b)
print("|c| =", mag_c)
print("|d| =", mag_d)

# (d)
print("\n(d) Productos escalares:")
print("a·b =", dot_ab)
print("a·c =", dot_ac)
print("a·d =", dot_ad)

# (e)
print("\n(e) Proyección de a sobre b:")
print("proj_b(a) =", proj_a_b)

# (f)
print("\n(f) Producto triple (coplanaridad):")
print("(a×b)·c =", triple)

# (g)
print("\n(g) (a + b)·(c + d) =", dot_sum)

# (h)
print("a×b =", axb)
print("b×c =", bxc)
print("c×d =", cxd)

# (i)
print("\n(i) c·(a×b) =", triple2)

"""Ejercicio 13 seccion 1.5.7"""

import sympy
from sympy import *
from sympy.vector import *

# Parámetro
t = symbols('t', real=True)

# Sistema de coordenadas
R = CoordSys3D('R')

# Parametrización del círculo de radio 1
x = cos(t)
y = sin(t)

# Campo de fuerza F
F = -(y/(x**2 + y**2))*R.i + (x/(x**2 + y**2))*R.j

# Vector diferencial dr
dr = diff(x, t)*R.i + diff(y, t)*R.j

# Producto punto F · dr
integrando = F.dot(dr)

# (a) Trabajo antihorario: t de 0 a 2π
W_a = integrate(integrando, (t, 0, 2*pi))

# (b) Trabajo horario: t de 0 a -2π
W_b = integrate(integrando, (t, 0, -2*pi))

W_a, W_b

print("\n(a) Trabajo antihorario:")
print("W =", W_a)

print("\n(b) Trabajo horario:")
print("W =", W_b)